### ISSUE TITLE
[Tracking] Support sourcing forc plugins from alternative repositories

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#162]
We'll soon need to handle retrieving forc plugins from multiple locations. This will include:

- `forc-wallet` https://github.com/FuelLabs/forc-wallet
- `forc-client` https://github.com/FuelLabs/sway/issues/2608
- `forc-explore` https://github.com/FuelLabs/sway/issues/2609

It might be useful to maintain a `forc-plugins.toml` index or something along these lines that we can use from both CI and from within `fuelup` itself so that we don't need to update multiple locations of source/tests each time we add/remove a plugin.

**Comment by bingcicle** [comment]
There's a few things to keep in mind here that might make this challenging:

1. We probably need some sort of standard when it comes to naming of the binary releases - for example, the Sway repo releases do not have their semver number in the name, while `fuel-core` does. The target triples that the Sway repo uses is also different from `fuel-core` (eg. forc is `amd64` versus fuel-core's `x86_64`). I chose to follow `fuel-core` in this regard when releasing `fuelup` binaries. 

The difference in naming of the binaries is also why [index-versions.sh](https://github.com/FuelLabs/fuelup/blob/168097bdcbf7f2ddb4f863da9da86d7bc022082b/.github/workflows/scripts/index-versions.sh) was a bit of a headache to deal with when adding `nightly` support. 

This isn't a problem for `fuelup`, more so for the CI since the CI handles bundling all the URLs into the channel toml, so `fuelup` doesn't have to think about how to format the URLs based on the tarball names.

2.  Which leads me to my next point, which is that the above could prove to be a problem if we want to add support for directly installing plugins from, say, a github repo. Though this is probably something far away, since we wouldn't really need `fuelup` to be able to do this unless we want devs to be able to download external plugins written by external contributors in the Fuel ecosystem. Perhaps the solution here is to just require external plugins to be downloaded with the full URL?

Maybe what we want is not really `forc-plugins.toml`, but rather `forc-components.toml` (I see plugins as a subset of components), i.e. `forc-explore` is a plugin, `forc`, the main tool, is a component. This also helps if we eventually want to distribute the indexer as well(?). This TOML file could contain info such as component name, executables, repository url and targets:

- name: the name of the component
- executables: the plugin may have several executables downloaded eg. `forc-client`
- repository_url: the distributed package can be named something different from the repo eg. sway -> forc
- targets: even right now, within `TargetTriple`, we're manually matching the component to the appropriate triple using `TargetTriple::from_component()`. This is used in commands like `fuelup component add`, `fuelup check`, `fuelup self update`

```toml
[forc]
name = "forc"
executables = ["forc"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

# This might be distributed together with `forc` above, but we should have a separate entry still.
[forc-fmt]
name = "forc-fmt"
is_plugin = true
executables = ["forc-fmt"]
repository_url = "https://github.com/FuelLabs/sway"
targets = ["linux_amd64", "linux_arm64", "darwin_amd64", "darwin_arm64"]

[fuel-core]
name = "fuel-core"
executables = ["fuel-core"]
repository_url = "https://github.com/FuelLabs/fuel-core"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]

[forc-wallet]
name = "forc-wallet"
is_plugin = true
executables = ["forc-wallet"]
repository_url = "https://github.com/FuelLabs/forc-wallet"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]

# when we eventually extract forc-client out:
[forc-client]
name = "forc-client"
is_plugin = true
executables = ["forc-deploy", "forc-run"]
repository_url = "https://github.com/FuelLabs/forc-client"
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "aarch64-apple-darwin", "x86_64-apple-darwin" ]
```

I was debating if we really need `targets` here, but if we want to reuse the same TOML file for both the CI and `fuelup`, then the CI needs to know the targets to be able to publish the URLs. Even so, there would still be _some_ manual logic needed, since some plugins are still distributed together with `forc` (`lsp`, `fmt`, etc.)
