### ISSUE TITLE
feat: allow specifying distributed toolchains with overriding versions in `fuel-toolchain.toml`

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#320]
Follow-up to https://github.com/FuelLabs/fuelup/pull/317

Currently in the `fuel-toolchain.toml` file, you can only specify components without specific versions and they download the `latest` versions:

```toml
[toolchain]
name = "my-toolchain"
components = ["forc"]
```

We want to allow:

```toml
[toolchain]
name = "my-toolchain"
components = ["forc@0.31.3"]
```

**Comment by mitchmindtree** [comment]
Not only do we want to allow this, but I think we may want to *require* this and treat the `fuel-toolchain` feature more like a lock file in general? I'll add more thoughts in #321.

**Comment by mitchmindtree** [comment]
Actually I take it back, I think we're on the write track as is :sweat_smile: 

Another option might be to handle components in a similar way to how we handle dependencies in forc.toml? E.g.

```toml
[toolchain]
name = "my-toolchain"

[components]
forc = "0.31.3"
```

That said, if the `forc@0.31.3` precedent is set by rustup, we're probably better off following that. There's also less complexity in components than there is in forc (i.e. there aren't different kinds of component sources).

**Comment by bingcicle** [comment]
I went with the `<name>@<version>` format to keep consistent with the input for `fuelup component add`, which also follows the same format. `rustup` AFAIK has [`components`](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) in an array, but I don't think they support specifying versions within each component, so we're on our own here :sweat: 

I think another benefit of declaring it in an array also means we can easily default to using `latest` if the dev didn't specify a version, otherwise we might have to force the user to type something even when not needed:

```toml
[toolchain]
name = "my-toolchain"

[components]
forc = "latest"
fuel-core = "0.14.1"
# other components below ...
```

Compared to

```toml
[toolchain]
name = "my-toolchain"
components = ["forc", "fuel-core@0.14.1"]
```

That said the parsing would've been a lot simpler if we used this way instead. Just finished writing the serde implementations for an `Option<Vec<Component>>` :sweat_smile: with that said though I'm open to changing the implementation if you think the 1st approach is cleaner!

**Comment by bingcicle** [comment]
Following #65 we should support overrides at a component-level. A sample of how this might look like:

```toml
[toolchain]
channel = "beta-2" # here, we're telling fuelup to use the beta-2 channel

[components]
forc = "0.32.2" # forc is on 0.31.3 on beta-2, but for whatever reason we might want forc on 0.32.2 instead
# Any unlisted components will be inherited from the `beta-2` toolchain.
```

**Comment by bingcicle** [comment]
This is closed by #335 #317 - overrides can now specify distributed toolchains, even those pinned to dates:

```toml
[toolchain]
channel = "latest-2023-01-18" # pinned to the `latest` published on 2023-01-18 (YYYY-MM-DD)

# any unlisted components will inherit from the `latest-2023-01-18` toolchain above
[components]
fuel-core = "0.14.1"
# other components below ...
```
