### ISSUE TITLE
support overrides for custom toolchains

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#325]
We should allow tomls of this format:

```toml
[components]
forc = "0.31.3"
# other components...
```

This lets users fully specify components without pinning to any specific channels (akin to custom toolchains)
