### ISSUE TITLE
feat: forbid `latest` in fuel-toolchain.toml

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#336]
As the title says - it might be **valid** to specify something like:

```toml
[toolchain]
channel = "latest"
```

but it probably isn't useful - reason being that we want to pin the toolchain to what was being used at that point in time, and `latest` isn't meaningful information.

What we want is something like:

```toml
[toolchain]
channel = "latest-2023-01-09"
```
