### ISSUE TITLE
bug: installing from override does not work

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#353]
Reported by @Braqzen:

With `fuelup v0.16.0`:

1. `forc new stst`
2. `cd stst`
3. use the below toml:

```toml
[toolchain]
channel = "latest-2023-01-17"

[components]
forc = "0.33.1"
fuel-core = "0.15.3"
```

4. `forc`

`forc` was not downloaded to the store.

The correct behaviour should mean that `forc` is downloaded to the store and the downloaded components linked to the toolchain directory.
