### ISSUE TITLE
feat: support `nightly` in overrides

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/fuelup#367]
We should support nightlies in overrides:

```toml
[toolchain]
channel = "latest-2023-01-18"

[components]
forc-explore = "0.28.1+nightly.20230126.4bb7392ed" # date and commit hash as seen here https://github.com/FuelLabs/sway-nightly-binaries/releases/tag/nightly-20230126
```
