### ISSUE TITLE
Support local binary paths in `fuel-toolchain.toml`

### ISSUE THREAD

**Issue by JoshuaBatty** [FuelLabs/fuelup#722]
## Overview
Currently, `fuel-toolchain.toml` only supports version numbers for components. Adding support for local binary paths would greatly improve the developer experience when working with local builds or custom versions of components.

## Related Issues
- #371 (Support nightly components in fuel-toolchain.toml)

Both issues aim to extend the component version specification system, though with different goals:
- #371 focuses on supporting nightly builds with date-based versioning
- This issue focuses on supporting local filesystem paths

## Proposed Syntax
```toml
[toolchain]
channel = "testnet"

[components]
forc = "/path/to/local/forc"
fuel-core = "0.41.7" # Mix local and versioned components
```

## Technical Requirements
1. Support absolute and relative paths (relative to fuel-toolchain.toml location)
2. Validate local binaries:
   - Ensure file exists and is executable

## Implementation Considerations
- Security implications of allowing arbitrary binary paths
